2024-04-26 00:20:47,491 INFO    StreamThr :7785 [internal.py:wandb_internal():86] W&B internal server running at pid: 7785, started at: 2024-04-26 00:20:47.489115
2024-04-26 00:20:47,494 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status
2024-04-26 00:20:47,517 INFO    WriterThread:7785 [datastore.py:open_for_write():87] open: /home/lwtaylor/ds3-audio/notebooks/wandb/run-20240426_002047-5tdlzupp/run-5tdlzupp.wandb
2024-04-26 00:20:47,518 DEBUG   SenderThread:7785 [sender.py:send():379] send: header
2024-04-26 00:20:47,643 DEBUG   SenderThread:7785 [sender.py:send():379] send: run
2024-04-26 00:20:47,844 ERROR   SenderThread:7785 [internal_api.py:execute():373] 404 response executing GraphQL.
2024-04-26 00:20:47,844 ERROR   SenderThread:7785 [internal_api.py:execute():374] {"errors":[{"message":"entity llava-chest-xray not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-04-26 00:20:47,845 ERROR   SenderThread:7785 [sender.py:send_run():971] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 969, in send_run
    server_run = self._init_run(run, config_value_dict)
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 1014, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2217, in upsert_run
    response = self.gql(
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/util.py", line 968, in check_retry_fn
    return fallback_retry_fn(e)
  File "/home/lwtaylor/.local/lib/python3.9/site-packages/wandb/util.py", line 910, in no_retry_auth
    raise CommError(
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-04-26 00:20:52,859 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:20:57,860 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:02,862 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:07,863 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:12,864 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:17,865 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:22,867 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:27,868 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:32,869 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:37,870 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:42,871 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:47,873 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:52,874 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:21:57,875 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:02,877 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:07,878 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:12,879 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:17,881 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:22,882 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:27,883 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:32,885 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:37,886 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:42,887 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:47,889 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:52,890 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:22:57,891 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:02,892 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:07,894 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:12,895 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:17,896 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:22,897 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:27,899 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:32,900 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:37,901 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:42,903 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:47,904 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:52,905 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:23:57,906 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:02,908 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:07,909 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:12,910 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:17,912 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:22,913 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:27,914 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:32,915 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:37,917 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:42,918 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:47,919 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:52,920 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:24:57,922 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:02,923 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:07,924 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:12,925 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:17,927 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:22,928 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:27,929 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:32,930 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:37,931 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: status_report
2024-04-26 00:25:39,036 DEBUG   HandlerThread:7785 [handler.py:handle_request():146] handle_request: shutdown
2024-04-26 00:25:39,036 INFO    HandlerThread:7785 [handler.py:finish():866] shutting down handler
2024-04-26 00:25:39,932 INFO    SenderThread:7785 [sender.py:finish():1546] shutting down sender
2024-04-26 00:25:39,936 INFO    WriterThread:7785 [datastore.py:close():296] close: /home/lwtaylor/ds3-audio/notebooks/wandb/run-20240426_002047-5tdlzupp/run-5tdlzupp.wandb
